version = "3.0.0"
dependencies = []
arch = "amd64"

[source.git-clone]
url = "https://github.com/InioX/matugen.git"
branch-or-tag = "v3.0.0"

[debian]
changelog = true
compat = 10

[debian.control]
description = "A material you color generation tool"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = ["CARGO_TERM_COLOR=always cargo build --release"]
override_dh_auto_install = [
    "install -Dm0755 target/release/matugen debian/matugen/usr/bin/matugen",
]
