version = "0.10.0-2"
dependencies = [
    "/shared/deb-latest/x-hyprwayland-scanner.deb",
    "/shared/deb-latest/x-hyprutils.deb",

    "libgles2-mesa-dev",

    "libseat-dev",
    "libinput-dev",
    "libwayland-dev",
    "wayland-protocols",
    "libpixman-1-dev",
    "libdrm-dev",
    "libgbm-dev",
    "libudev-dev",
    "libdisplay-info-dev",
    "hwdata",
    # "libpugixml-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/aquamarine.git"
branch-or-tag = "v0.10.0"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Aquamarine is a very light linux rendering backend library"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/x-aquamarine/usr",
]
