version = "0.53.1"
dependencies = [
    "/shared/deb-latest/x-hyprutils.deb",
    "/shared/deb-latest/x-aquamarine.deb",
    "/shared/deb-latest/x-hyprlang.deb",
    "/shared/deb-latest/x-hyprcursor.deb",
    "/shared/deb-latest/x-hyprgraphics.deb",
    "/shared/deb-latest/x-hyprwayland-scanner.deb",
    "/shared/deb-latest/x-hyprland-protocols.deb",
    "/shared/deb-latest/x-hyprwire.deb",

    "libgles2-mesa-dev",

    "libxkbcommon-dev",
    "uuid-dev",
    "libwayland-dev",
    "wayland-protocols",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libpixman-1-dev",
    "libxcursor-dev",
    "libdrm-dev",
    "libinput-dev",
    "libgbm-dev",
    "libgio-2.0-dev",
    "libre2-dev",

    # for XWayland (see NO_XWAYLAND)
    "libxcb-xfixes0-dev",
    "libxcb-icccm4-dev",
    "libxcb-composite0-dev",
    "libxcb-res0-dev",
    "libxcb-errors-dev",

    "libtomlplusplus-dev",
    "libmuparser-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprland.git"
branch-or-tag = "v0.53.1"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Hyprland is an independent, highly customizable, dynamic tiling Wayland compositor that doesn't sacrifice on its looks."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:STRING=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/x-hyprland/usr",
    "rm debian/x-hyprland/usr/share/hypr/wall*.png",
]
override_dh_usrlocal = ["@true"]
