version = "0.1.13-7"
dependencies = [
    "/shared/deb-latest/x-hyprutils.deb",
    "/shared/deb-latest/x-hyprlang.deb",

    "libzip-dev",
    "libcairo2-dev",
    "librsvg2-dev",
    "libtomlplusplus-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprcursor.git"
branch-or-tag = "v0.1.13"

[debian]
changelog = true
compat = 10

[debian.control]
description = "The hyprland cursor format, library and utilities."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/x-hyprcursor/usr",
]
