version = "0.3.3-4"
dependencies = [
    "/shared/deb-latest/x-hyprlang.deb",
    "/shared/deb-latest/x-hyprutils.deb",
    "/shared/deb-latest/x-hyprwayland-scanner.deb",
    "/shared/deb-latest/x-hyprland-protocols.deb",

    "libwayland-dev",
    "wayland-protocols",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprsunset.git"
branch-or-tag = "v0.3.3"

[debian]
changelog = true
compat = 10

[debian.control]
description = "An application to enable a blue-light filter on Hyprland"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/x-hyprsunset/usr",
]
