version = "0.5.2"
dependencies = [
    "/shared/deb-latest/x-hyprwayland-scanner.deb",
    "/shared/deb-latest/x-hyprutils.deb",
    "/shared/deb-latest/x-hyprlang.deb",
    "/shared/deb-latest/x-hyprgraphics.deb",
    "/shared/deb-latest/x-aquamarine.deb",

    "libgles2-mesa-dev",

    "libwayland-dev",
    "wayland-protocols",
    "libpixman-1-dev",
    "libdrm-dev",
    "libgbm-dev",
    "libxkbcommon-dev",
    "libpango1.0-dev",
    "libcairo2-dev",
    "libiniparser-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprtoolkit.git"
branch-or-tag = "v0.5.2"

[debian]
changelog = true
compat = 10

[debian.control]
description = "A modern C++ Wayland-native GUI toolkit"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/x-hyprtoolkit/usr",
]
