version = "0.4.0"
dependencies = [
    "/shared/deb-latest/x-hyprutils.deb",
    "libpixman-1-dev",
    "libcairo2-dev",
    "libjpeg-dev",
    "libwebp-dev",
    "libmagic-dev",
    "libspng-dev",
    "libpango1.0-dev",
    "librsvg2-dev",

    # opt
    "libjxl-dev",
    "libheif-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprgraphics.git"
branch-or-tag = "v0.4.0"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Hyprland graphics / resource utilities"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/x-hyprgraphics/usr",
]
